if landing.html exists, overwrite the index.html generated by docusaurus
openziti/ziti-doc pull request #621
Opened 2023-08-04 11:32 UTC by dovholuknf

in order to allow for easier deployment of a landing page from otherly-generated content, allow the index.html file to be stomped by process. if landing.html exists, it'll be deployed as the index.html

2023-08-04 12:49 UTC, qrkourier requested changes, later dismissed

2023-08-04 12:49 UTC, qrkourier commented on docusaurus/docusaurus.config.js
> +          href: 'https://openziti.io/',
Allows the button to work wherever the site is hosted, e.g., locally or Vercel, too.

```suggestion
          href: '/',
```

2023-08-04 12:49 UTC, qrkourier commented on gendoc.sh
> +echo "gendoc complete"
```suggestion
echo "gendoc complete"

```

2023-08-07 14:49 UTC, dovholuknf commented on docusaurus/docusaurus.config.js
> +          href: 'https://openziti.io/',
please put a branch up for this and verify it works. i want to commit what we have as is to make sure this process works

2023-08-07 14:56 UTC, qrkourier commented on docusaurus/docusaurus.config.js
> +          href: 'https://openziti.io/',
I tested it locally, but I can send a twig PR too.

2023-08-07 15:06 UTC, qrkourier commented on docusaurus/docusaurus.config.js
> +          href: 'https://openziti.io/',
twig PR: https://github.com/openziti/ziti-doc/pull/629

2023-08-07 15:08 UTC, qrkourier requested changes
twig PR: https://github.com/openziti/ziti-doc/pull/629

2023-08-07 15:43 UTC, qrkourier approved these changes
Missing newline at `gendoc.sh` end of file @dovholuknf

2023-08-07 15:43 UTC, qrkourier commented on gendoc.sh
> +echo "gendoc complete"
Missing newline at end of file @dovholuknf

2023-08-07 17:47 UTC, gberl002 approved these changes

2023-08-07 17:51 UTC, merged