Breakfix/miniziti refactor issues
openziti/ziti-doc pull request #679
Opened 2023-09-08 22:47 UTC by sabedevops

2023-09-08 22:48 UTC, sabedevops commented
@dovholuknf && @qrkourier This restores miniziti functionality. Can we please get this merged? There are a few, minor outstanding issues I will address through this branch later, but for now, this gets things back to sanity and working.

2023-09-11 13:26 UTC, qrkourier requested changes
Should we double-check the output token files to ensure they resemble a JWT? At a minimum, a `test -s`, but perhaps a minimum byte count?

2023-09-11 13:26 UTC, qrkourier commented on docusaurus/docs/learn/quickstarts/network/miniziti.bash
> +            #ziti edge logout --cli-identity "$MINIKUBE_PROFILE" >&3
If this is intentionally commented, then why not also remove the enclosing check and log message?

2023-09-11 15:18 UTC, sabedevops commented
> Should we double-check the output token files to ensure they resemble a JWT? At a minimum, a `test -s`, but perhaps a minimum byte count?

I've added `--exit-status` to `jq` instead.

2023-09-11 15:29 UTC, qrkourier approved these changes

2023-09-11 15:32 UTC, merged